CREATE TABLE CE_USERS (
    CE_USER_ID SERIAL PRIMARY KEY,
    CE_ORGANIZATION_ID BIGINT NOT NULL UNIQUE,
    CE_USER_FIRSTNAME VARCHAR(255) NOT NULL,
    CE_USER_LASTNAME VARCHAR(255) NOT NULL,
    CE_USER_EMAIL VARCHAR(255) UNIQUE,
    CE_USER_ROLE VARCHAR(50) NOT NULL,
    CE_USER_UNIQUE_CODE VARCHAR(255) UNIQUE,
    CE_IS_ACTIVATED VARCHAR(10)
);
