CREATE TABLE CE_USERS (
    CE_USER_ID SERIAL PRIMARY KEY,
    CE_NAME VARCHAR(255),
    CE_EMAIL VARCHAR(255) UNIQUE
);

CREATE TABLE CE_COURSES (
    CE_COURSE_ID SERIAL PRIMARY KEY,
    CE_COURSE_NAME VARCHAR(255),
    CE_DESCRIPTION TEXT
);