<!DOCTYPE html>
<html>
<head>
    <title>${subject}</title>
</head>
<body>
    <h1>Hello, ${messageBody}!</h1>

    <p>You have been successfully added to your organization. Welcome aboard!</p>

    <p>Your unique code for account activation is: <strong>${uniqueCode}</strong></p>

    <p>You can reset your password by visiting the <a href="http://localhost:3000/register">Register</a> tab.</p>

    <p>Best Regards,<br>CtrlEdu Team</p>
</body>
</html>
