CREATE SEQUENCE organization_id_seq START 100000 INCREMENT BY 1 NO MAXVALUE;

CREATE TABLE CE_TENANTS (
    CE_TENANT_ID SERIAL PRIMARY KEY,
    CE_ORGANIZATION_ID INT UNIQUE NOT NULL DEFAULT nextval('organization_id_seq'),
    CE_ORGANIZATION_NAME VARCHAR(255),
    CE_SCHEMA_NAME VARCHAR(255) UNIQUE,
    CE_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
